# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-10.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-10.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kang/code/Maze

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kang/code/Maze

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-10.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-10.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kang/code/Maze/CMakeFiles /Users/kang/code/Maze/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kang/code/Maze/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Maze.exe

# Build rule for target.
Maze.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Maze.exe
.PHONY : Maze.exe

# fast build rule for target.
Maze.exe/fast:
	$(MAKE) -f CMakeFiles/Maze.exe.dir/build.make CMakeFiles/Maze.exe.dir/build
.PHONY : Maze.exe/fast

#=============================================================================
# Target rules for targets named maze

# Build rule for target.
maze: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 maze
.PHONY : maze

# fast build rule for target.
maze/fast:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/build
.PHONY : maze/fast

A_star.o: A_star.cpp.o
.PHONY : A_star.o

# target to build an object file
A_star.cpp.o:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/A_star.cpp.o
.PHONY : A_star.cpp.o

A_star.i: A_star.cpp.i
.PHONY : A_star.i

# target to preprocess a source file
A_star.cpp.i:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/A_star.cpp.i
.PHONY : A_star.cpp.i

A_star.s: A_star.cpp.s
.PHONY : A_star.s

# target to generate assembly for a file
A_star.cpp.s:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/A_star.cpp.s
.PHONY : A_star.cpp.s

Algorithm.o: Algorithm.cpp.o
.PHONY : Algorithm.o

# target to build an object file
Algorithm.cpp.o:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/Algorithm.cpp.o
.PHONY : Algorithm.cpp.o

Algorithm.i: Algorithm.cpp.i
.PHONY : Algorithm.i

# target to preprocess a source file
Algorithm.cpp.i:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/Algorithm.cpp.i
.PHONY : Algorithm.cpp.i

Algorithm.s: Algorithm.cpp.s
.PHONY : Algorithm.s

# target to generate assembly for a file
Algorithm.cpp.s:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/Algorithm.cpp.s
.PHONY : Algorithm.cpp.s

DFS_L.o: DFS_L.cpp.o
.PHONY : DFS_L.o

# target to build an object file
DFS_L.cpp.o:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/DFS_L.cpp.o
.PHONY : DFS_L.cpp.o

DFS_L.i: DFS_L.cpp.i
.PHONY : DFS_L.i

# target to preprocess a source file
DFS_L.cpp.i:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/DFS_L.cpp.i
.PHONY : DFS_L.cpp.i

DFS_L.s: DFS_L.cpp.s
.PHONY : DFS_L.s

# target to generate assembly for a file
DFS_L.cpp.s:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/DFS_L.cpp.s
.PHONY : DFS_L.cpp.s

DFS_R.o: DFS_R.cpp.o
.PHONY : DFS_R.o

# target to build an object file
DFS_R.cpp.o:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/DFS_R.cpp.o
.PHONY : DFS_R.cpp.o

DFS_R.i: DFS_R.cpp.i
.PHONY : DFS_R.i

# target to preprocess a source file
DFS_R.cpp.i:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/DFS_R.cpp.i
.PHONY : DFS_R.cpp.i

DFS_R.s: DFS_R.cpp.s
.PHONY : DFS_R.s

# target to generate assembly for a file
DFS_R.cpp.s:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/DFS_R.cpp.s
.PHONY : DFS_R.cpp.s

DisjSets.o: DisjSets.cpp.o
.PHONY : DisjSets.o

# target to build an object file
DisjSets.cpp.o:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/DisjSets.cpp.o
.PHONY : DisjSets.cpp.o

DisjSets.i: DisjSets.cpp.i
.PHONY : DisjSets.i

# target to preprocess a source file
DisjSets.cpp.i:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/DisjSets.cpp.i
.PHONY : DisjSets.cpp.i

DisjSets.s: DisjSets.cpp.s
.PHONY : DisjSets.s

# target to generate assembly for a file
DisjSets.cpp.s:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/DisjSets.cpp.s
.PHONY : DisjSets.cpp.s

Maze.o: Maze.cpp.o
.PHONY : Maze.o

# target to build an object file
Maze.cpp.o:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/Maze.cpp.o
.PHONY : Maze.cpp.o

Maze.i: Maze.cpp.i
.PHONY : Maze.i

# target to preprocess a source file
Maze.cpp.i:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/Maze.cpp.i
.PHONY : Maze.cpp.i

Maze.s: Maze.cpp.s
.PHONY : Maze.s

# target to generate assembly for a file
Maze.cpp.s:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/Maze.cpp.s
.PHONY : Maze.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Maze.exe.dir/build.make CMakeFiles/Maze.exe.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Maze.exe.dir/build.make CMakeFiles/Maze.exe.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Maze.exe.dir/build.make CMakeFiles/Maze.exe.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Maze.exe"
	@echo "... edit_cache"
	@echo "... maze"
	@echo "... rebuild_cache"
	@echo "... A_star.o"
	@echo "... A_star.i"
	@echo "... A_star.s"
	@echo "... Algorithm.o"
	@echo "... Algorithm.i"
	@echo "... Algorithm.s"
	@echo "... DFS_L.o"
	@echo "... DFS_L.i"
	@echo "... DFS_L.s"
	@echo "... DFS_R.o"
	@echo "... DFS_R.i"
	@echo "... DFS_R.s"
	@echo "... DisjSets.o"
	@echo "... DisjSets.i"
	@echo "... DisjSets.s"
	@echo "... Maze.o"
	@echo "... Maze.i"
	@echo "... Maze.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
